qtreports::Engine
bool qtreports::Engine::m_isOpened
Referenced by open, close, isOpened.
QString qtreports::Engine::m_lastError
Referenced by open, setParameters, setConnection, setDataSource, createPDF, createHTML, createWidget, createLayout, print, drawPreview, prepareDataSource, getLastError.
QString qtreports::Engine::m_compiledPath
Referenced by open, close.
detail::ReportPtr qtreports::Engine::m_report
Referenced by open, close, setParameters, setConnection, setQuery, createPDF, createHTML, createWidget, createLayout, print, drawPreview, prepareDB, prepareDataSource, getReport.
QVector< QString > qtreports::Engine::m_scripts
Referenced by addScript.
QSqlDatabase qtreports::Engine::m_dbConnection
Referenced by setConnection, executeQueries.
qtreports::Engine::Engine(QObject *parent=Q_NULLPTR)
qtreports::Engine::Engine(const QString &path, QObject *parent=Q_NULLPTR)
References open.
qtreports::Engine::~Engine()
bool qtreports::Engine::open(const QString &path)
Загружает макет отчета из файла path.
path полное имя макета отчета
References isOpened, close, qtreports::detail::ParserFromXML::parse, m_lastError, qtreports::detail::ParserFromXML::getLastError, m_isOpened, m_compiledPath, m_report, qtreports::detail::ParserFromXML::getReport, qtreports::detail::ParserFromXML::getLog.
Referenced by Engine.
void qtreports::Engine::close()
Выгружает из оперативной памяти данные об отчете
References m_isOpened, m_compiledPath, m_report.
Referenced by open.
bool qtreports::Engine::setParameters(const QMap< QString, QVariant > &map)
Передает карту параметров в отчет, для успешной передачи параметров не обязатеьно загружать их описание с макетом отчета
map карта параметров в формате (< имя="" параметра>="">, < значение="" параметра>="">)
References m_report, m_lastError.
bool qtreports::Engine::setConnection(const QSqlDatabase &connection)
Устанавливает источник данных для отчета из БД
connection соединение с БД
References m_lastError, m_report, m_dbConnection, prepareDB.
bool qtreports::Engine::setDataSource(const QMap< QString, QVector< QVariant > > &columnsSet)
Устанавливает источник данных для отчета из таблицы полей
columnsSet набор данных в формате (< имя="" столбца>="">, < вектор="" значений="" столбца>="">)
References prepareDataSource, m_lastError.
bool qtreports::Engine::setQuery(const QString &query)
Устанавливает запрос, по которому будут заполнятся поля отчета
query запрос
References m_report, executeQueries.
Referenced by prepareDB.
bool qtreports::Engine::addScript(const QString &script)
Добавить скрипт для отчета
script скрипт
References m_scripts.
bool qtreports::Engine::setDataModel(const QAbstractItemModel &model)
bool qtreports::Engine::createPDF(const QString &path)
Создает PDF документ отчета по указанному пути
path полное имя выходного документа
References m_report, m_lastError, qtreports::detail::ConverterToPDF::convert, qtreports::detail::ConverterToPDF::getLastError.
bool qtreports::Engine::createHTML(const QString &path)
Создает HTML документ отчета по указанному пути
path полное имя выходного документа
References m_report, m_lastError, qtreports::detail::ConverterToHTML::convert, qtreports::detail::ConverterToHTML::getLastError.
QWidgetPtr qtreports::Engine::createWidget()
Создает виджет отчета для вывода на экран.
References m_report, m_lastError, qtreports::detail::ConverterToQWidget::convert, qtreports::detail::ConverterToQWidget::Report, qtreports::detail::ConverterToQWidget::getLastError, qtreports::detail::ConverterToQWidget::getQWidget.
QWidgetPtr qtreports::Engine::createLayout()
References m_report, m_lastError, qtreports::detail::ConverterToQWidget::convert, qtreports::detail::ConverterToQWidget::Layout, qtreports::detail::ConverterToQWidget::getLastError, qtreports::detail::ConverterToQWidget::getQWidget.
bool qtreports::Engine::print()
References m_report, m_lastError, prepareDB, drawPreview.
bool qtreports::Engine::isOpened() const
Возвращает true в случае учпешной загрузки отчета, иначе - false.
References m_isOpened.
Referenced by open.
detail::ReportPtr qtreports::Engine::getReport() const
References m_report.
const QString qtreports::Engine::getLastError() const
References m_lastError.
void qtreports::Engine::drawPreview(QPrinter *printer)
References m_report, qtreports::detail::ConverterToQWidget::convert, qtreports::detail::ConverterToQWidget::Report, m_lastError, qtreports::detail::ConverterToQWidget::getLastError, qtreports::detail::ConverterToQWidget::getPages.
Referenced by print.
bool qtreports::Engine::prepareDB()
References setQuery, m_report.
Referenced by setConnection, print.
bool qtreports::Engine::prepareDataSource(const QMap< QString, QVector< QVariant > > &source)
References m_lastError, m_report.
Referenced by setDataSource, executeQueries.
bool qtreports::Engine::executeQueries(const QStringList &queries)
References m_dbConnection, prepareDataSource.
Referenced by setQuery.