qtreports::detail::Replacer
QString qtreports::detail::Replacer::m_lastError
Referenced by replaceParametersInSection, replaceParameters, replaceFieldInSection, getLastError.
qtreports::detail::Replacer::Replacer()
qtreports::detail::Replacer::~Replacer()
QString qtreports::detail::Replacer::replaceParameters(const QString &text, const ReportPtr &report)
Возвращает текст с подставленными значениями параметров.
text Исходный текст report Указатель на отчет
Referenced by replaceParametersInTextWidget, replace.
bool qtreports::detail::Replacer::replaceParametersInTextWidget(const TextWidgetPtr &widget, const ReportPtr &report)
Заменяет текст виджета текстом с подставленными значениями параметров.
Перегружанная функция, предоставленная для удобства. widget Указатель на виджет report Указатель на отчет
References replaceParameters.
Referenced by replaceParametersInSection.
bool qtreports::detail::Replacer::replaceParametersInSection(const SectionPtr &section, const ReportPtr &report)
Заменяет текст всех виджетов секции текстом с подставленными значениями параметров.
Перегружанная функция, предоставленная для удобства. section Указатель на секцию report Указатель на отчет
References m_lastError, replaceParametersInTextWidget.
Referenced by replaceParameters.
bool qtreports::detail::Replacer::replaceParameters(const ReportPtr &report)
Заменяет текст всех виджетов с текстом в отчете текстом с подставленными значениями параметров.
Перегружанная функция, предоставленная для удобства. report Указатель на отчет
References m_lastError, replaceParametersInSection.
QString qtreports::detail::Replacer::replaceField(const QString &text, const ReportPtr &report, int i)
Возвращает текст с подставленными значениями полей из источника данных.
text Исходный текст report Указатель на отчет i Текущая строка
Referenced by qtreports::detail::ConverterToHTML::addGroupsIntoReport, qtreports::detail::ConverterToPDF::addGroupsIntoReport, qtreports::detail::ConverterToQWidget::addGroupsIntoReport, replaceRowGroupInCrosstab, replaceColumnGroupInCrosstab, replaceCellInCrosstab, replaceFieldInTextWidget.
QImage qtreports::detail::Replacer::replaceFieldImage(const QString &text, const ReportPtr &report, int i)
Возвращает изображение на основе первого найденного выражения.
text Исходный текст report Указатель на отчет i Текущая строка
Referenced by replaceFieldInImageWidget.
bool qtreports::detail::Replacer::replaceColumnGroupsInCrosstab(const CrosstabPtr &crosstab, const ReportPtr &report, QList< QString > &columnGroups)
References replaceColumnGroupInCrosstab.
Referenced by qtreports::detail::ConverterToPDF::createBands, qtreports::detail::ConverterToQWidget::createBands.
bool qtreports::detail::Replacer::replaceRowGroupsInCrosstab(const CrosstabPtr &crosstab, const ReportPtr &report, QList< QString > &rowGroups)
References replaceRowGroupInCrosstab.
Referenced by qtreports::detail::ConverterToPDF::createBands, qtreports::detail::ConverterToQWidget::createBands.
bool qtreports::detail::Replacer::replaceRowGroupInCrosstab(const CrosstabPtr &crosstab, const ReportPtr &report, int i)
References replaceField.
Referenced by replaceRowGroupsInCrosstab.
bool qtreports::detail::Replacer::replaceColumnGroupInCrosstab(const CrosstabPtr &crosstab, const ReportPtr &report, int i)
References replaceField.
Referenced by replaceColumnGroupsInCrosstab.
bool qtreports::detail::Replacer::replaceCellInCrosstab(const CrosstabPtr &crosstab, const ReportPtr &report, int i)
References replaceField.
bool qtreports::detail::Replacer::replaceFieldInTextWidget(const TextWidgetPtr &widget, const ReportPtr &report, int i)
Заменяет текст виджета текстом с подставленными значениями полей из источника данных.
Перегружанная функция, предоставленная для удобства. widget Указатель на виджет report Указатель на отчет i Текущая строка
References replaceField.
Referenced by replaceFieldInSection.
bool qtreports::detail::Replacer::replaceFieldInImageWidget(const ImagePtr &widget, const ReportPtr &report, int i)
На основе текста виджета вставляет в него изображение из источника данных.
Перегружанная функция, предоставленная для удобства. widget Указатель на виджет report Указатель на отчет i Текущая строка
References replaceFieldImage.
Referenced by replaceFieldInSection.
bool qtreports::detail::Replacer::replaceFieldInSection(const SectionPtr &section, const ReportPtr &report, int i)
Заменяет текст всех виджетов секции текстом с подставленными значениями полей из источника данных.
Перегружанная функция, предоставленная для удобства. section Указатель на секцию report Указатель на отчет i Текущая строка
References m_lastError, replaceFieldInTextWidget, replaceFieldInImageWidget.
Referenced by replace.
bool qtreports::detail::Replacer::replace(const SectionPtr &section, const ReportPtr &report, int i)
Заменяет текст всех виджетов секции текстом с подставленными значениями.
Перегружанная функция, предоставленная для удобства. section Указатель на секцию report Указатель на отчет i Текущая строка
References replaceFieldInSection, replaceParameters.
Referenced by qtreports::detail::ConverterToHTML::addBands, qtreports::detail::ConverterToPDF::createSection, qtreports::detail::ConverterToQWidget::createSection.
const QString qtreports::detail::Replacer::getLastError() const
Возвращает описание последней произошедшей ошибки.
References m_lastError.
Referenced by qtreports::detail::ConverterToHTML::addBands, qtreports::detail::ConverterToPDF::createSection, qtreports::detail::ConverterToQWidget::createSection.