qtreports::detail::ConverterToQWidget
WidgetType
Отчет
ReportPtr qtreports::detail::ConverterToQWidget::m_report
Указатель на отчет, который будет конвертироваться.
Referenced by convert, addPage, createQWidget, createSection, createBands.
QString qtreports::detail::ConverterToQWidget::m_lastError
Содержит информацию о последней ошибке, возникшей в процессе конвертации.
Referenced by getLastError, createQWidget, createSection, createBands.
QWidgetPtr qtreports::detail::ConverterToQWidget::m_qwidget
Указатель на создаваемый QWidget.
Referenced by getQWidget, createQWidget.
WidgetType qtreports::detail::ConverterToQWidget::m_type
Содержит информацию о типе виждета.
ConverterToQWidget::WidgetType
Referenced by convert, isReport, isLayout, getType.
QVector< QWidgetPtr > qtreports::detail::ConverterToQWidget::m_pages
Содержит список страниц создаваемого виждета.
Referenced by getPage, getPages, addPage, createBands.
int qtreports::detail::ConverterToQWidget::m_currentHeight
Содержит текущую высоту виджета.
ConverterToQWidget::WidgetType
Referenced by createBands.
qtreports::detail::ConverterToQWidget::ConverterToQWidget(const ReportPtr &report)
Конструктор по умолчанию.
report ссылка на объект ReportPtr.
qtreports::detail::ConverterToQWidget::~ConverterToQWidget()
bool qtreports::detail::ConverterToQWidget::convert(WidgetType type=WidgetType::Report)
Конвертирует отчет в виджет.
По умолчанию тип виджета WidgetType::Report. true , если конвертация отчета в виджет прошла успешно, иначеfalse . ConverterToQWidget::WidgetType
References m_type, createQWidget, m_report.
Referenced by qtreports::Engine::createWidget, qtreports::Engine::createLayout, qtreports::Engine::drawPreview.
bool qtreports::detail::ConverterToQWidget::isReport() const
Проверяет, является ли виджет типа WidgetType::Report.
true , если виджет типа WidgetType::Report, иначеfalse . ConverterToQWidget::WidgetType
References m_type, Report.
Referenced by addGroupsIntoReport.
bool qtreports::detail::ConverterToQWidget::isLayout() const
Проверяет, является ли виджет типа WidgetType::Layout.
true , если виджет типа WidgetType::Layout, иначеfalse . ConverterToQWidget::WidgetType
References m_type, Layout.
Referenced by addVerticalBorder, addEmptySection, addSectionLayout, createQWidget, addGroupsIntoReport, createSection, createBands.
ConverterToQWidget::WidgetType qtreports::detail::ConverterToQWidget::getType() const
Возвращает текущий тип виджета.
References m_type.
const QWidgetPtr qtreports::detail::ConverterToQWidget::getQWidget() const
Возвращает указатель на объект QWidget.
Если объект QWidget не был создан, то возвращаетсяnullptr .
References m_qwidget.
Referenced by qtreports::Engine::createWidget, qtreports::Engine::createLayout.
const QWidgetPtr qtreports::detail::ConverterToQWidget::getPage(int i) const
Возвращает указатель страницы виджета по индексу.
References m_pages.
const QVector< QWidgetPtr > qtreports::detail::ConverterToQWidget::getPages() const
Возвращает список всех страниц виджета.
References m_pages.
Referenced by qtreports::Engine::drawPreview.
const QString qtreports::detail::ConverterToQWidget::getLastError() const
Возвращает информацию о последней ошибке, возникшей в процессе конвертации.
References m_lastError.
Referenced by qtreports::Engine::createWidget, qtreports::Engine::createLayout, qtreports::Engine::drawPreview.
void qtreports::detail::ConverterToQWidget::addVerticalBorder(QBoxLayout *parent, const QMargins &margins, int height)
Добавляет вертикальную границу.
parent Указатель на QBoxLayout, на который добавляется вертикальная граница. margins Содержит информацию об отступах для данного QBoxLayout. height Значение высоты секции.
References isLayout, qtreports::detail::createLayout.
Referenced by createQWidget.
void qtreports::detail::ConverterToQWidget::addEmptySection(QBoxLayout *parent, const QMargins &margins)
Добавляет пустую секцию.
parent Указатель на QBoxLayout, на который пустая секция. margins Содержит информацию об отступах для данного QBoxLayout.
References isLayout, qtreports::detail::createLayout.
Referenced by createQWidget.
QFrame * qtreports::detail::ConverterToQWidget::addSectionLayout(QBoxLayout *parent, const QMargins &margins, int height)
Добавляет секцию.
parent Указатель на QBoxLayout, на который добавляется секция. margins Содержит информацию об отступах для данного QBoxLayout. height Значение высоты секции.
References isLayout, qtreports::detail::createLayout.
Referenced by createQWidget, addGroupsIntoReport.
void qtreports::detail::ConverterToQWidget::addPage()
Добавляет новую страницу на виджет.
References m_report, m_pages.
Referenced by createQWidget, createBands.
bool qtreports::detail::ConverterToQWidget::addGroupsIntoReport(const ReportPtr &report, const DetailPtr &detail, QVBoxLayout *layout)
Функция добавления группировок в отчет.
report Указатель на отчет, с которым ведется работа. detail Указатель на блок detail, в котором будут отображаться данные. layout Указатель на layout, который является непосредственным контейнером данных. true, если добавление группы произошло успешно, иначе false.
References qtreports::detail::Replacer::replaceField, isLayout, addSectionLayout, createSection, isReport.
Referenced by createQWidget.
bool qtreports::detail::ConverterToQWidget::createQWidget(const ReportPtr &report)
Конвертирует отчет в QWidget.
report Указатель на отчет, с которым ведется работа. true, если добавление группы произошло успешно, иначе false.
References m_lastError, m_qwidget, addPage, addVerticalBorder, isLayout, addSectionLayout, createSection, addGroupsIntoReport, m_report, addEmptySection.
Referenced by convert.
bool qtreports::detail::ConverterToQWidget::createSection(QWidget *parent, const SectionPtr &section, int i)
Создает секцию.
Если не удалось создать секцию, вернет false. Информация об ошибке содержится в переменной m_lastError. parent указатель на объект QWidget, на котором создается секция. section Ссылка на объект SectionPtr. SectionPtr может указывать на такие секции, как: title,header,footer,detail . i Индекс текущей секции. true , если создание секции прошло успешно, иначеfalse .
References isLayout, qtreports::detail::Replacer::replace, m_report, m_lastError, qtreports::detail::Replacer::getLastError, createBands.
Referenced by createQWidget, addGroupsIntoReport.
bool qtreports::detail::ConverterToQWidget::createBands(QWidget *parent, const SectionPtr &section)
Создает band.
parent указатель на объект QWidget, на котором создается band. section Ссылка на объект SectionPtr. true , если создание bsnd'a прошло успешно, иначеfalse .
References m_currentHeight, m_report, addPage, isLayout, m_pages, m_lastError, qtreports::detail::Replacer::replaceColumnGroupsInCrosstab, qtreports::detail::Replacer::replaceRowGroupsInCrosstab.
Referenced by createSection.