qtreports::detail::Style
bool qtreports::detail::Style::m_isDefault
Referenced by isDefault, setAsDefault.
bool qtreports::detail::Style::m_isBold
Referenced by isBold, setBold.
bool qtreports::detail::Style::m_isItalic
Referenced by isItalic, setItalic.
bool qtreports::detail::Style::m_isUnderline
Referenced by isUnderline, setUnderline.
bool qtreports::detail::Style::m_isStrikeThrough
Referenced by isStrikeThrough, setStrikeThrough.
int qtreports::detail::Style::m_fontSize
Referenced by getFontSize, setFontSize.
bool qtreports::detail::Style::m_isPDFEmbedded
Referenced by isPDFEmbedded, setPDFEmbedded.
QColor qtreports::detail::Style::m_fontColor
Referenced by getFontColor, setFontColor.
QString qtreports::detail::Style::m_fontName
Referenced by getFontName, setFontName.
QString qtreports::detail::Style::m_pdfFontName
Referenced by getPDFFontName, setPDFFontName.
QString qtreports::detail::Style::m_pdfEncoding
Referenced by getPDFEncoding, setPDFEncoding.
qtreports::detail::Style::Style()
qtreports::detail::Style::~Style()
bool qtreports::detail::Style::isDefault() const
Возвращает, является ли данный стиль стилем по умолчанию
References m_isDefault.
void qtreports::detail::Style::setAsDefault(bool flag)
Устанавливает, является ли текущий стиль стилем по умолчанию
flag Новое значение
References m_isDefault.
const QString qtreports::detail::Style::getFontName() const
Возвращает название шрифта
References m_fontName.
Referenced by qtreports::detail::ConverterToHTML::createHTML.
void qtreports::detail::Style::setFontName(const QString &name)
Устанавливает название шрифта
name Название шрифта
References m_fontName.
int qtreports::detail::Style::getFontSize() const
Возвращает размер шрифта
References m_fontSize.
Referenced by qtreports::detail::ConverterToHTML::createHTML.
void qtreports::detail::Style::setFontSize(int size)
Устанавливает размер шрифта
size Размер шрифта
References m_fontSize.
const QColor qtreports::detail::Style::getFontColor() const
Возвращает цвет шрифта
References m_fontColor.
Referenced by qtreports::detail::ConverterToHTML::createHTML.
void qtreports::detail::Style::setFontColor(const QColor &color)
Устанавливает цвет шрифта
color Цвет шрифта
References m_fontColor.
bool qtreports::detail::Style::isBold() const
Возвращает, является ли шрифт жирным или нет
References m_isBold.
Referenced by qtreports::detail::ConverterToHTML::createHTML.
void qtreports::detail::Style::setBold(bool flag)
Устанавливает, является ли шрифт жирным или нет
flag Новое значение
References m_isBold.
bool qtreports::detail::Style::isItalic() const
Возвращает, является ли шрифт курсивом или нет
References m_isItalic.
Referenced by qtreports::detail::ConverterToHTML::createHTML.
void qtreports::detail::Style::setItalic(bool flag)
Устанавливает, является ли шрифт курсивом или нет
flag Новое значение
References m_isItalic.
bool qtreports::detail::Style::isUnderline() const
Возвращает, является ли шрифт подчеркнутым или нет
References m_isUnderline.
void qtreports::detail::Style::setUnderline(bool flag)
Устанавливает, является ли шрифт подчеркнутым или нет
flag Новое значение
References m_isUnderline.
bool qtreports::detail::Style::isStrikeThrough() const
Возвращает, является ли шрифт перечеркнутым или нет
References m_isStrikeThrough.
void qtreports::detail::Style::setStrikeThrough(bool flag)
Устанавливает, является ли шрифт перечеркнутым или нет
flag Новое значение
References m_isStrikeThrough.
const QString qtreports::detail::Style::getPDFFontName() const
Возвращает название шрифта в PDF.
References m_pdfFontName.
void qtreports::detail::Style::setPDFFontName(const QString &name)
Устанавливает название шрифта в PDF.
name Название шрифта
References m_pdfFontName.
const QString qtreports::detail::Style::getPDFEncoding() const
Возвращает название кодировки в PDF.
References m_pdfEncoding.
void qtreports::detail::Style::setPDFEncoding(const QString &encoding)
Устанавливает название кодировки в PDF.
encoding Название кодировки
References m_pdfEncoding.
bool qtreports::detail::Style::isPDFEmbedded() const
Возвращает ...
в PDF
References m_isPDFEmbedded.
void qtreports::detail::Style::setPDFEmbedded(bool isEmbedded)
Устанавливает ...
в PDF isEmbedded Новое значение
References m_isPDFEmbedded.