qtreports::detail::Field
QString qtreports::detail::Field::m_className
Referenced by setClassName, getClassName.
QVector< QVariant > qtreports::detail::Field::m_data
Referenced by setData, getData, getRowCount, getDataVar, setDataVar.
qtreports::detail::Field::Field()
qtreports::detail::Field::~Field()
void qtreports::detail::Field::setClassName(const QString &name)
Устанавливает атрибут className.
name Название класса
References m_className.
const QString qtreports::detail::Field::getClassName() const
Возвращает атрибут className.
References m_className.
void qtreports::detail::Field::setData(const QVector< QVariant > &data)
Устанавливает содержимое <field>
data Вектор, содержащие данные <field>
References m_data.
QString qtreports::detail::Field::getData(int row)
Возвращает содержимое <field>
row Номер строки
References m_data.
const T1 qtreports::detail::Field::getData(int row)
Возвращает содержимое <field>.
Шаблонный вариант. row Номер строки
References m_data, getDataVar, setDataVar, getRowCount.
const QVariant qtreports::detail::Field::getDataVar(int row)
References m_data.
Referenced by getData.
void qtreports::detail::Field::setDataVar(int row, const QVariant &value)
References m_data.
Referenced by getData.
int qtreports::detail::Field::getRowCount()
Получить количество строк в <field>
References m_data.
Referenced by getData.