qtreports::detail::ConverterToPDF
ReportPtr qtreports::detail::ConverterToPDF::m_report
Объект класса ReportPtr.
Referenced by create, createSection, createBands.
QString qtreports::detail::ConverterToPDF::m_lastError
Содержит информацию о последней ошибке, возникшей в процессе конвертации.
Referenced by create, createSection, getLastError.
int qtreports::detail::ConverterToPDF::m_currentResolution
Значение текущего разрешения для PDF документа в DPI.
По умолчанию установлено значение 75.
Referenced by setDPI, getDPI, create.
int qtreports::detail::ConverterToPDF::m_currentHeight
Значение текущей высоты кисти, рисующей на листе документа PDF.
Значение постоянно меняется в зависимости от высоты band. Например, если в отчете для band'а, который отрисовывается в данный момент, значение параметра height равняется 35, то после отрисовки данного band'а, кисть переместится вниз на 35 единиц.
Referenced by createBands.
qtreports::detail::ConverterToPDF::ConverterToPDF(const ReportPtr &report)
Конструктор по умолчанию.
report ссылка на объект ReportPtr.
qtreports::detail::ConverterToPDF::~ConverterToPDF()
bool qtreports::detail::ConverterToPDF::convert(const QString &path)
Запускает процесс конвертации.
Путь может быть полным или относительным, примеры: "C:/example.pdf" "example.pdf" path Путь, по которому будет создан PDF документ. true , если конвертация отчета в PDF прошла успешно, иначеfalse .
References create.
Referenced by qtreports::Engine::createPDF.
void qtreports::detail::ConverterToPDF::setDPI(int dpi)
Устанавливает DPI.
dpi Новое значение DPI.
References m_currentResolution.
int qtreports::detail::ConverterToPDF::getDPI() const
Возвращает текущее значение DPI.
References m_currentResolution.
const QString qtreports::detail::ConverterToPDF::getLastError() const
Возвращает строку, содержащую описание последней произошедшей ошибки.
References m_lastError.
Referenced by qtreports::Engine::createPDF.
bool qtreports::detail::ConverterToPDF::addGroupsIntoReport(QPdfWriter &writer, QPainter &painter, const ReportPtr &report, const DetailPtr &detail)
Добавляет группу в репорт.
Если не удалось добавить группу, вернет false. writer Ссылка на объект QPdfWriter. painter Ссылка на объект QPainter. report Ссылка на объект ReportPtr. detail Ссылка на объект DetailPtr. true , если добавление группы прошло успешно, иначеfalse .
References qtreports::detail::Replacer::replaceField, createSection.
Referenced by create.
bool qtreports::detail::ConverterToPDF::create(const QString &path)
Конвертирует отчет в PDF документ.
Если не удалось конвертировать в PDF, вернет false. Информация об ошибке содержится в переменной m_lastError. path Путь к файлу PDF. true , если конвертация прошла успешно, иначеfalse .
References m_report, m_lastError, m_currentResolution, createSection, addGroupsIntoReport.
Referenced by convert.
bool qtreports::detail::ConverterToPDF::createSection(QPdfWriter &writer, QPainter &painter, const SectionPtr &section, int i)
Создает секцию.
Если не удалось создать секцию, вернет false. Информация об ошибке содержится в переменной m_lastError. writer Ссылка на объект QPdfWriter. painter Ссылка на объект QPainter. section Ссылка на объект SectionPtr. SectionPtr может указывать на такие секции, как: title,header,footer,detail . i Индекс текущей секции. true , если создание секции прошло успешно, иначеfalse .
References qtreports::detail::Replacer::replace, m_report, m_lastError, qtreports::detail::Replacer::getLastError, createBands.
Referenced by create, addGroupsIntoReport.
bool qtreports::detail::ConverterToPDF::createBands(QPdfWriter &writer, QPainter &painter, const SectionPtr &section)
Создает band.
writer Ссылка на объект QPdfWriter. painter Ссылка на объект QPainter. section Ссылка на объект SectionPtr. true , если создание bsnd'a прошло успешно, иначеfalse .
References m_currentHeight, m_report.
Referenced by createSection.