qtreports::detail::ConverterToHTML
ReportPtr qtreports::detail::ConverterToHTML::m_report
Объект класса ReportPtr.
Referenced by createHTML, addGroupsIntoReport, addBands.
QString qtreports::detail::ConverterToHTML::m_lastError
Содержит информацию о последней ошибке, возникшей в процессе конвертации.
Referenced by convert, createHTML, addBands, getLastError.
QString qtreports::detail::ConverterToHTML::m_html
Содержит текст документа в формате HTML.
Referenced by convert, createHTML, addBands, getHTML.
QString qtreports::detail::ConverterToHTML::m_defaultStyleName
Содержит название стиля по умолчанию.
Referenced by createHTML, addBands.
qtreports::detail::ConverterToHTML::ConverterToHTML(const ReportPtr &report)
Конструктор по умолчанию.
report ссылка на объект ReportPtr.
qtreports::detail::ConverterToHTML::~ConverterToHTML()
bool qtreports::detail::ConverterToHTML::convert()
Запускает процесс конвертации репорта в HTML формат.
true если конвертация прошла успешно. false если конвертация не удалась.
References createHTML.
Referenced by convert, qtreports::Engine::createHTML.
bool qtreports::detail::ConverterToHTML::convert(const QString &path)
Создает HTML документ при успешной конвертации репорта в HTML формат.
Путь может быть полным или относительным, примеры: "C:/example.html" "example.html" path Путь, по которому будет создан HTML документ. true если создание файла прошло успешно. false если создание файла не удалось.
References convert, m_lastError, m_html.
const QString qtreports::detail::ConverterToHTML::getLastError() const
Получить описание последней произошедшей ошибки.
Строка с описанием последней произошедшей ошибки.
References m_lastError.
Referenced by qtreports::Engine::createHTML.
const QString qtreports::detail::ConverterToHTML::getHTML() const
Получить документ в HTML формате.
Строка с документом в HTML формате.
References m_html.
bool qtreports::detail::ConverterToHTML::createHTML()
Процесс конвертации репорта в HTML формат.
true если конвертация прошла успешно. false если конвертация не удалась.
References m_report, m_lastError, m_html, m_defaultStyleName, qtreports::detail::Style::getFontName, qtreports::detail::Style::getFontSize, qtreports::detail::Style::getFontColor, qtreports::detail::Style::isItalic, qtreports::detail::Style::isBold, addBands, addGroupsIntoReport.
Referenced by convert.
bool qtreports::detail::ConverterToHTML::addGroupsIntoReport(QSharedPointer< Detail > detail)
Добавление <group> в документ HTML.
detail Ссылка на объект Detail. true если добавление прошло успешно. false если добавление не удалось.
References m_report, qtreports::detail::Replacer::replaceField, addBands.
Referenced by createHTML.
bool qtreports::detail::ConverterToHTML::addBands(QSharedPointer< Section > section, int sectionIndex)
Добавление <band>, принадлежащего конкретной <section>, в документ HTML.
section Ссылка на объект Section. Может указывать на такие секции, как: title,header,footer,detail sectionIndex Индекс конкретной секции. true если добавление прошло успешно. false если добавление не удалось.
References qtreports::detail::Replacer::replace, m_report, m_lastError, qtreports::detail::Replacer::getLastError, m_defaultStyleName, addShapes, m_html.
Referenced by createHTML, addGroupsIntoReport.
void qtreports::detail::ConverterToHTML::addShapes(QSharedPointer< Band > band, QString &elementStr)
Добавление <shape>, принадлежащего конретному <band>, в документ HTML.
band Ссылка на объект Band. elemenStr Строка с содержимым band.
Referenced by addBands.