qtreports::detail::ParserFromXML
AttributeOption
При отсутствии аттрибута будет выдана ошибка.
using qtreports::detail::ParserFromXML::ParseFuncPtr = bool( QXmlStreamReader &, const ObjectPtr & )
using qtreports::detail::ParserFromXML::ParseMethodPtr = bool( ParserFromXML::* )( QXmlStreamReader &, const ObjectPtr & )
using qtreports::detail::ParserFromXML::ParseFunc = std::function< ParseFuncPtr >
ReportPtr qtreports::detail::ParserFromXML::m_report
Referenced by parse, parseDocument, getReport.
QString qtreports::detail::ParserFromXML::m_lastError
Referenced by parse, getValue, getAttribute, goToElementEnd, parseChilds, parseStyle, getLastError.
QTextStream qtreports::detail::ParserFromXML::m_log
Referenced by parse, getValue, getAttribute, goToElementEnd, parseChilds, getLog.
QMap< QString, ParseFunc > qtreports::detail::ParserFromXML::m_functions
Referenced by ParserFromXML, parseChilds.
qtreports::detail::ParserFromXML::ParserFromXML()
References m_functions, qtreports::detail::toParseFunc, parseReport, parseStyle, parseQueryString, parseField, parseGroup, parseGroupExpression, parseGroupHeader, parseGroupFooter, parseTitle, parseDetail, parseSummary, parseBand, parseStaticText, parseTextField, parseLine, parseRect, parseEllipse, parseImage, parseImageExpression, parseReportElement, parseTextElement, parseFont, parseText, parseTextFieldExpression, parseCrosstab, parseRowGroup, parseColumnGroup, parseCrosstabCell, parseCrosstabRowHeader, parseCrosstabColumnHeader, parseCrosstabCellContents, parseVariable, parseVariableExpression, parseInitialValueExpression.
qtreports::detail::ParserFromXML::~ParserFromXML()
bool qtreports::detail::ParserFromXML::parse(const QString &path)
Парсит отчет и создает из него внутреннюю структуру данных Report.
path Путь к отчету формата .qreport
References m_report, m_lastError, m_log, parseDocument.
Referenced by qtreports::Engine::open.
const ReportPtr qtreports::detail::ParserFromXML::getReport() const
Возвращает указатель на внутреннюю структуру отчета.
Указатель может быть пустым, перед использованием необходимо проверить с помощью if(!report.isNull()){
References m_report.
Referenced by qtreports::Engine::open.
const QString qtreports::detail::ParserFromXML::getLastError() const
Возвращает описание последней произошедшей ошибки.
References m_lastError.
Referenced by qtreports::Engine::open.
const QString qtreports::detail::ParserFromXML::getLog() const
Возвращает лог процесса парсинга.
Используется для отладки при добавлении новый тэгов.
References m_log.
Referenced by qtreports::Engine::open.
bool qtreports::detail::ParserFromXML::getValue(QXmlStreamReader &reader, QString &data)
Считывает xml элемент в data.
reader QXmlStreamReader [out] data считанные данные
References m_log, m_lastError.
Referenced by parseGroupExpression, parseText, parseTextFieldExpression, parseImageExpression, parseVariableExpression, parseInitialValueExpression, parseQueryString.
bool qtreports::detail::ParserFromXML::getAttribute(QXmlStreamReader &reader, const QString &name, QString &data, AttributeOption option)
Записывает в data значение аттрибута с именем name текущего тэга
reader QXmlStreamReader name имя аттрибута option указывает обязателен ли атрибут [out] data считанные данные
References m_log, Optional, m_lastError.
Referenced by getRequiredAttribute, getOptionalAttribute.
bool qtreports::detail::ParserFromXML::getRequiredAttribute(QXmlStreamReader &reader, const QString &name, QString &data)
Вызывает функцию getAttribute с переданными параметрами и с параметром option - "обязательный аттрибут".
References getAttribute, Required.
Referenced by parseReport, parseStyle, parseField, parseGroup, parseBand, parseRowGroup, parseColumnGroup, parseCrosstabCell, parseReportElement, parseTextElement, parseTextFieldExpression, parseVariable.
bool qtreports::detail::ParserFromXML::getOptionalAttribute(QXmlStreamReader &reader, const QString &name, QString &data)
Вызывает функцию getAttribute с переданными параметрами и с параметром option - "опциональный аттрибут".
References getAttribute, Optional.
Referenced by parseReport, parseStyle, parseRowGroup, parseColumnGroup, parseReportElement, parseTextElement, parseFont.
bool qtreports::detail::ParserFromXML::goToElementEnd(QXmlStreamReader &reader)
Устанавлиает курсор reader(а) к к началу следующего тэга или к концу документа
References m_log, m_lastError.
Referenced by parseChilds, parseReportElement, parseFont.
bool qtreports::detail::ParserFromXML::parseChilds(QXmlStreamReader &reader, const ObjectPtr &object)
Парсит дочерние тэги объекта object.
object родительский объект отчета
References m_log, m_functions, goToElementEnd, m_lastError.
Referenced by parseDocument, parseReport, parseField, parseGroup, parseGroupHeader, parseGroupFooter, parseTitle, parseDetail, parseSummary, parseBand, parseCrosstab, parseRowGroup, parseColumnGroup, parseCrosstabCell, parseCrosstabRowHeader, parseCrosstabColumnHeader, parseCrosstabCellContents, parseStaticText, parseTextField, parseLine, parseRect, parseEllipse, parseImage, parseTextElement, parseVariable.
bool qtreports::detail::ParserFromXML::parseDocument(const QString &text)
Начинает парсинг документа
text имя xml файла
References m_report, qtreports::detail::Report, parseChilds.
Referenced by parse.
bool qtreports::detail::ParserFromXML::parseReport(QXmlStreamReader &reader, const ReportPtr &report)
Парсит тэг report.
report указатель на объект отчета
References getRequiredAttribute, getOptionalAttribute, parseChilds, qtreports::detail::isEquals.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseStyle(QXmlStreamReader &reader, const ReportPtr &report)
Парсит тэг style.
report указатель на объект отчета
References getRequiredAttribute, getOptionalAttribute, m_lastError, qtreports::detail::toBool.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseQueryString(QXmlStreamReader &reader, const ReportPtr &report)
Парсит запросы
report указатель на объект отчета
References getValue.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseField(QXmlStreamReader &reader, const ReportPtr &report)
Парсит тэг Field.
report указатель на объект отчета
References getRequiredAttribute, parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseGroup(QXmlStreamReader &reader, const ReportPtr &report)
Парсит тэг group.
report указатель на объект отчета
References getRequiredAttribute, qtreports::detail::Group, parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseGroupExpression(QXmlStreamReader &reader, const GroupPtr &group)
Парсит тэг groupExpression.
group указатель на группу, которой принадлежит groupExpression
References getValue.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseGroupHeader(QXmlStreamReader &reader, const GroupPtr &group)
Парсит тэг groupHeader.
group указатель на группу, которой принадлежит groupHeader
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseGroupFooter(QXmlStreamReader &reader, const GroupPtr &group)
Парсит тэг groupFooter.
group указатель на группу, которой принадлежит groupFooter
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseTitle(QXmlStreamReader &reader, const ReportPtr &report)
Парсит тэг Title.
report указатель на объект отчета
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseDetail(QXmlStreamReader &reader, const ReportPtr &report)
Парсит тэг Detail.
report указатель на объект отчета
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseSummary(QXmlStreamReader &reader, const ReportPtr &report)
Парсит тэг Summary.
report указатель на объект отчета
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseBand(QXmlStreamReader &reader, const SectionPtr &section)
Парсит тэг Band.
section секция (объект, содержащий Band(ы), Detail, Title, groupHeader и т.д.), которой принадлежит Band
References getRequiredAttribute, parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseCrosstab(QXmlStreamReader &reader, const BandPtr &band)
Парсит тэг Crosstab.
band Строка, которой принадлежит объект
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseRowGroup(QXmlStreamReader &reader, const CrosstabPtr &crosstab)
Парсит тэг rowGroup.
crosstab Кросстаб, которому принадлежит объект
References getRequiredAttribute, getOptionalAttribute, parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseColumnGroup(QXmlStreamReader &reader, const CrosstabPtr &crosstab)
Парсит тэг columnGroup.
crosstab Кросстаб, которому принадлежит объект
References getRequiredAttribute, getOptionalAttribute, parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseCrosstabCell(QXmlStreamReader &reader, const CrosstabPtr &crosstab)
Парсит тэг crosstabCell.
crosstab Кросстаб, которому принадлежит объект
References getRequiredAttribute, parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseCrosstabRowHeader(QXmlStreamReader &reader, const CrosstabGroupPtr &rowGroup)
Парсит тэг crosstabRowHeader.
rowGroup Группа кросстаба, которому принадлежит объект
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseCrosstabColumnHeader(QXmlStreamReader &reader, const CrosstabGroupPtr &columnGroup)
Парсит тэг crosstabColumnHeader.
columnGroup Группа кросстаба, которому принадлежит объект
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseCrosstabCellContents(QXmlStreamReader &reader, const CrosstabCellPtr &crosstabSection)
Парсит тэг cellContents.
crosstabSection Секция кросстаба, которому принадлежит объект
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseStaticText(QXmlStreamReader &reader, const BandPtr &band)
Парсит тэг StaticText.
band Строка, которой принадлежит объект
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseTextField(QXmlStreamReader &reader, const WidgetPtr &widget)
Парсит тэг TextField.
band Строка, которой принадлежит объектVariablePtr
References parseChilds, qtreports::detail::Band::addTextField, qtreports::detail::CellContents::setTextField.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseLine(QXmlStreamReader &reader, const BandPtr &band)
Парсит тэг Line.
band Строка, которой принадлежит объект
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseRect(QXmlStreamReader &reader, const BandPtr &band)
Парсит тэг Rect.
band Строка, которой принадлежит объект
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseEllipse(QXmlStreamReader &reader, const BandPtr &band)
Парсит тэг Ellipse.
band Строка, которой принадлежит объект
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseImage(QXmlStreamReader &reader, const BandPtr &band)
Парсит тэг Image.
band Строка, которой принадлежит объект
References parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseReportElement(QXmlStreamReader &reader, const WidgetPtr &widget)
Парсит тэг ReportElement - общие данные о элементе отчета (положение, размеры и пр.)
widget общий класс для объектов, подлежащих отображению. Для него загружается текущий reportElement
References getRequiredAttribute, getOptionalAttribute, goToElementEnd.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseTextElement(QXmlStreamReader &reader, const WidgetPtr &widget)
Парсит тэг TextElement - общие данные о текстовом элементе (выравнивание текста и пр.)
widget общий класс для объектов, подлежащих отображению. Для него загружается текущий textElement
References getRequiredAttribute, getOptionalAttribute, parseChilds, qtreports::detail::isEquals.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseFont(QXmlStreamReader &reader, const WidgetPtr &widget)
Парсит font - данные о шрифте текста
widget общий класс для объектов, подлежащих отображению. Для него загружается текущий font
References getOptionalAttribute, goToElementEnd, qtreports::detail::toBool.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseText(QXmlStreamReader &reader, const StaticTextPtr &text)
Парсит текст для staticText.
text staticText, текущий объект
References getValue.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseTextFieldExpression(QXmlStreamReader &reader, const TextFieldPtr &text)
Парсит текст для textField.
text textField, текущий объект
References getRequiredAttribute, getValue.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseImageExpression(QXmlStreamReader &reader, const ImagePtr &image)
Парсит текст (imageExpression) для image.
image тэг image, текущий объект
References getValue.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseVariable(QXmlStreamReader &reader, const ReportPtr &report)
References getRequiredAttribute, qtreports::detail::None, qtreports::detail::Report, qtreports::detail::Page, qtreports::detail::Column, qtreports::detail::Group, qtreports::detail::Count, qtreports::detail::Sum, qtreports::detail::Average, qtreports::detail::Lowest, qtreports::detail::Highest, parseChilds.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseVariableExpression(QXmlStreamReader &reader, const VariablePtr &variable)
References getValue.
Referenced by ParserFromXML.
bool qtreports::detail::ParserFromXML::parseInitialValueExpression(QXmlStreamReader &reader, const VariablePtr &variable)
References getValue.
Referenced by ParserFromXML.