qtreports::detail
VariableResetType
VariableIncrementType
VariableCalculation
typedef QSharedPointer< Report > qtreports::detail::ReportPtr
typedef QSharedPointer< Band > qtreports::detail::BandPtr
typedef QSharedPointer<Box> qtreports::detail::BoxPtr
typedef QSharedPointer<CellContents> qtreports::detail::CellContentsPtr
typedef QSharedPointer<Crosstab> qtreports::detail::CrosstabPtr
typedef QSharedPointer<CrosstabCell> qtreports::detail::CrosstabCellPtr
typedef QSharedPointer<CrosstabGroup> qtreports::detail::CrosstabGroupPtr
typedef qtreports::detail::CrosstabGroup::GroupType qtreports::detail::CrosstabGroupType
typedef QSharedPointer<CrosstabHeader> qtreports::detail::CrosstabHeaderPtr
typedef QSharedPointer< Detail > qtreports::detail::DetailPtr
typedef QSharedPointer< Ellipse > qtreports::detail::EllipsePtr
typedef QSharedPointer< Field > qtreports::detail::FieldPtr
typedef QSharedPointer< Group > qtreports::detail::GroupPtr
typedef QSharedPointer< Image > qtreports::detail::ImagePtr
typedef QSharedPointer< Line > qtreports::detail::LinePtr
typedef QSharedPointer< Object > qtreports::detail::ObjectPtr
typedef QSharedPointer< QueryString > qtreports::detail::QueryStringPtr
typedef QSharedPointer< Rect > qtreports::detail::RectPtr
typedef QSharedPointer< Section > qtreports::detail::SectionPtr
typedef QSharedPointer< StaticText > qtreports::detail::StaticTextPtr
typedef QSharedPointer< Style > qtreports::detail::StylePtr
typedef QSharedPointer<Summary> qtreports::detail::SummaryPtr
typedef QSharedPointer< TextField > qtreports::detail::TextFieldPtr
typedef QSharedPointer< TextWidget > qtreports::detail::TextWidgetPtr
typedef QSharedPointer< Title > qtreports::detail::TitlePtr
typedef QSharedPointer< Variable > qtreports::detail::VariablePtr
typedef QSharedPointer< Widget > qtreports::detail::WidgetPtr
QHBoxLayout* qtreports::detail::createLayout(QWidget *left, QWidget *center, QWidget *right)
Referenced by qtreports::detail::ConverterToQWidget::addVerticalBorder, qtreports::detail::ConverterToQWidget::addEmptySection, qtreports::detail::ConverterToQWidget::addSectionLayout.
ParserFromXML::ParseFunc qtreports::detail::bindParseFunc(ParserFromXML *obj, ParserFromXML::ParseMethodPtr method)
Referenced by toParseFunc.
ParserFromXML::ParseFunc qtreports::detail::toParseFunc(ParserFromXML *obj, bool(ParserFromXML::*method)(QXmlStreamReader &, const T1 &))
References bindParseFunc.
Referenced by qtreports::detail::ParserFromXML::ParserFromXML.
bool qtreports::detail::toBool(const QString &string)
References isEquals.
Referenced by qtreports::detail::ParserFromXML::parseStyle, qtreports::detail::ParserFromXML::parseFont.
bool qtreports::detail::isEquals(const QString &string1, const QString &string2)
Referenced by toBool, qtreports::detail::ParserFromXML::parseReport, qtreports::detail::ParserFromXML::parseTextElement.