qtreports::detail::Report
QPrinter::Orientation qtreports::detail::Report::m_orientation
Referenced by setOrientation, getOrientation, getSize.
QSize qtreports::detail::Report::m_size
Referenced by setSize, getSize, setWidth, setHeight.
QMargins qtreports::detail::Report::m_margins
Referenced by setLeftMargin, getLeftMargin, setTopMargin, getTopMargin, setRightMargin, getRightMargin, setBottomMargin, getBottomMargin, setMargins, getMargins.
StylePtr qtreports::detail::Report::m_defaultStyle
Referenced by setDefaultStyle, getDefaultStyle.
QMap< QString, StylePtr > qtreports::detail::Report::m_styles
Referenced by addStyle, getStyle, getStyles.
QString qtreports::detail::Report::m_query
Referenced by setQuery, getQuery.
QMap< QString, FieldPtr > qtreports::detail::Report::m_fields
Referenced by setField, getField, getFields, getFieldsDataCount.
QMap< QString, GroupPtr > qtreports::detail::Report::m_groups
Referenced by addGroup, getGroup, getGroups, getGroupByIndex.
TitlePtr qtreports::detail::Report::m_title
Referenced by setTitle, getTitle.
DetailPtr qtreports::detail::Report::m_detail
Referenced by setDetail, getDetail.
SummaryPtr qtreports::detail::Report::m_summary
Referenced by setSummary, getSummary.
QMap< QString, QVariant > qtreports::detail::Report::m_parameters
Referenced by setParameter, setParameters, getParameter, getParameters.
QMap< QString, VariablePtr > qtreports::detail::Report::m_variables
Referenced by addVaraible, getVariable, getVariables.
QMap< QString, QVector<int> > qtreports::detail::Report::m_groupsData
Referenced by fillGroupsData, GetGroupsData.
QVector<bool> qtreports::detail::Report::m_group_vec
qtreports::detail::Report::Report()
qtreports::detail::Report::~Report()
void qtreports::detail::Report::setDefaultStyle(const StylePtr &style)
References m_defaultStyle.
const StylePtr qtreports::detail::Report::getDefaultStyle() const
References m_defaultStyle.
void qtreports::detail::Report::addStyle(const QString &name, const StylePtr &style)
References m_styles.
const StylePtr qtreports::detail::Report::getStyle(const QString &name) const
References m_styles.
const QMap< QString, StylePtr > & qtreports::detail::Report::getStyles() const
References m_styles.
void qtreports::detail::Report::addGroup(const QString &name, const GroupPtr &group)
References m_groups.
const GroupPtr qtreports::detail::Report::getGroup(const QString &name) const
References m_groups.
const QMap< QString, GroupPtr > qtreports::detail::Report::getGroups() const
References m_groups.
Referenced by fillGroupsData.
void qtreports::detail::Report::setQuery(const QString &query)
References m_query.
const QString qtreports::detail::Report::getQuery() const
References m_query.
void qtreports::detail::Report::setField(const QString &name, const FieldPtr &field)
References m_fields.
const FieldPtr qtreports::detail::Report::getField(const QString &name) const
References m_fields.
Referenced by setFieldData.
const QMap< QString, FieldPtr > qtreports::detail::Report::getFields() const
References m_fields.
Referenced by getRowCount.
int qtreports::detail::Report::getFieldsDataCount() const
References m_fields.
void qtreports::detail::Report::setFieldData(const QString &name, const QVector< QVariant > &data)
References getField.
void qtreports::detail::Report::setTitle(const TitlePtr &title)
References m_title.
const TitlePtr qtreports::detail::Report::getTitle() const
References m_title.
void qtreports::detail::Report::setDetail(const DetailPtr &detail)
References m_detail.
const DetailPtr qtreports::detail::Report::getDetail() const
References m_detail.
void qtreports::detail::Report::setSummary(const SummaryPtr &summary)
References m_summary.
const SummaryPtr qtreports::detail::Report::getSummary() const
References m_summary.
void qtreports::detail::Report::setParameter(const QString &name, const QVariant &value)
References m_parameters.
void qtreports::detail::Report::setParameters(const QMap< QString, QVariant > &parameters)
References m_parameters.
const QVariant qtreports::detail::Report::getParameter(const QString &name) const
References m_parameters.
const QMap< QString, QVariant > qtreports::detail::Report::getParameters() const
References m_parameters.
int qtreports::detail::Report::getRowCount() const
References getFields.
Referenced by fillGroupsData.
void qtreports::detail::Report::setOrientation(QPrinter::Orientation orientation)
References m_orientation.
QPrinter::Orientation qtreports::detail::Report::getOrientation() const
References m_orientation.
void qtreports::detail::Report::setSize(const QSize &size)
References m_size.
const QSize qtreports::detail::Report::getSize() const
References m_orientation, m_size.
Referenced by getWidth, getHeight.
void qtreports::detail::Report::setWidth(int width)
References m_size.
int qtreports::detail::Report::getWidth() const
References getSize.
void qtreports::detail::Report::setHeight(int height)
References m_size.
int qtreports::detail::Report::getHeight() const
References getSize.
void qtreports::detail::Report::setLeftMargin(int left)
References m_margins.
Referenced by setMargins.
int qtreports::detail::Report::getLeftMargin() const
References m_margins.
void qtreports::detail::Report::setTopMargin(int top)
References m_margins.
Referenced by setMargins.
int qtreports::detail::Report::getTopMargin() const
References m_margins.
void qtreports::detail::Report::setRightMargin(int right)
References m_margins.
Referenced by setMargins.
int qtreports::detail::Report::getRightMargin() const
References m_margins.
void qtreports::detail::Report::setBottomMargin(int bottom)
References m_margins.
Referenced by setMargins.
int qtreports::detail::Report::getBottomMargin() const
References m_margins.
void qtreports::detail::Report::setMargins(int left, int top, int right, int bottom)
References setLeftMargin, setTopMargin, setRightMargin, setBottomMargin.
void qtreports::detail::Report::setMargins(const QMargins &margins)
References m_margins.
const QMargins qtreports::detail::Report::getMargins() const
References m_margins.
GroupPtr qtreports::detail::Report::getGroupByIndex(int index)
References m_groups.
void qtreports::detail::Report::addVaraible(const VariablePtr &variable)
References m_variables.
const VariablePtr qtreports::detail::Report::getVariable(const QString &name) const
References m_variables.
const QMap< QString, VariablePtr > & qtreports::detail::Report::getVariables() const
References m_variables.
void qtreports::detail::Report::fillGroupsData(const QSharedPointer< Report > &reportPtr)
References getGroups, getRowCount, m_groupsData, qtreports::detail::Replacer::replaceField.
const QMap< QString, QVector< int > > qtreports::detail::Report::GetGroupsData() const
References m_groupsData.